blank_issues_enabled: false
contact_links:
  - name: Support and Questions
    url: "https://help.elyranur.com/"
    about: "If you have trouble with setting up Elyranur, please use the forum instead of opening an issue here."
